features:
  node_user_picture: 0
  comment_user_picture: 0
  comment_user_verification: 0
  favicon: 1
logo:
  use_default: 0
  path: 'public://hcaslogo2_medium.png'
favicon:
  use_default: 0
  path: 'public://favicon.ico'
  mimetype: image/vnd.microsoft.icon
mobile_menu_all_widths: 0
site_branding_bg_color: default
base_primary_color: '#cf7618'
