_core:
  default_config_hash: 1TswGK46jyu77aIM7Z-0JVQs5bxHmo-gtgrvrQGMXxc
favicon:
  mimetype: image/vnd.microsoft.icon
  path: 'public://favicon.ico'
  use_default: false
features:
  comment_user_picture: false
  comment_user_verification: false
  favicon: true
  node_user_picture: false
logo:
  path: 'public://gl_hcaslogo2_medium.png'
  use_default: false
third_party_settings:
  shortcut:
    module_link: true
mobile_menu_all_widths: 0
site_branding_bg_color: default
base_primary_color: '#cf7618'
